name: Build
on:
  push:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  Build-Folia:
    if: (github.event_name == 'pull_request' && github.event.action == 'labeled') || github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.11.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
      - name: Apply Patches and Build
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./gradlew applyPatches --stacktrace
          ./gradlew build --stacktrace
          ./gradlew createReobfBundlerJar
      - uses: actions/upload-artifact@v3
        with:
         name: Folia
         path: build/libs/*.jar
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         automatic_release_tag: "latest"
         prerelease: false
         title: "Folia 自动构建最新版本"
         files: build/libs/*.jar
